### ISSUE TITLE
More Information - Issue about file names, appearance of playable .wav in Gradio

### ISSUE THREAD

**Issue by MackNcD** [daswer123/xtts-webui#1]
So the image of the soundwave and the playable .wav itself don't show up, I wasn't able to fix it. But I did make some alterations to the naming system -- you can add in the  UUID information if you need it but for my personal uses, I found this format (there's an extra input field that allows you to index you sound files how you want -- really important for stitching many files together) (also, added in a versioning count because often the way something is written needs to edited once and again for the spoken version to sound right, so a count system was added. 

part one edited:

#gen1
def generate_audio(text, languages, speaker_value_text, speaker_path_text, additional_text, temperature, length_penalty, repetition_penalty, top_k, top_p, speed, sentence_split):

    ref_speaker_wav = ""

    if speaker_path_text and speaker_value_text == "reference":
        ref_speaker_wav = speaker_path_text 
    else:
        ref_speaker_wav = speaker_value_text 

    lang_code = reversed_supported_languages[languages]
    options = {
        "temperature": temperature,
        "length_penalty": length_penalty,
        "repetition_penalty": float(repetition_penalty),
        "top_k": top_k,
        "top_p": top_p,
        "speed": speed,
        "sentence_split": sentence_split,
    }

    # Check if the file already exists, if yes, add a number to the filename
    count = 1
    output_file_path = f"{additional_text}_({count})_{speaker_value_text}.wav"
    while os.path.exists(os.path.join('output', output_file_path)):
        count += 1
        output_file_path = f"{additional_text}_({count})_{speaker_value_text}.wav"

    # Perform TTS and save to the generated filename
    output_file = XTTS.process_tts_to_file(text, lang_code, ref_speaker_wav, options, output_file_path)

    return gr.make_waveform(audio=output_file),output_file

part 2 edited

        with gr.Column():
            video_gr = gr.Video(label="Waveform Visual",interactive=False)
            audio_gr = gr.Audio(label="Synthesised Audio",interactive=False, autoplay=False)
            generate_btn = gr.Button(value="Generate",size="lg")
            
            additional_text_input = gr.Textbox(label="File Name Value", value="user_input")

            generate_btn.click(
                fn=generate_audio,
                inputs=[text, languages, speaker_value_text, speaker_path_text, additional_text_input, temperature, length_penalty, repetition_penalty, top_k, top_p, speed, sentence_split],
                outputs=[video_gr, audio_gr]
            )

**Comment by MackNcD** [comment]
Apologies, just saw what a mess that was, broke it down into just the one column's edits and the generate functions edits

**Comment by daswer123** [comment]
Thanks for the code, I added your code
https://github.com/daswer123/xtts-webui/commit/1a039af36e295262dda45c2ad34d78a56d581ed2

**Comment by MackNcD** [comment]
Excellent. I also fixed an issue with the local port resorting to the default 7860, instead of the one listed in the .py/the one you mentioned (5003? Something about that) 
There's also a way to get a file to play, and I'm pretty sure it's possible to do so with an added audio/visual wave, which I've been trying to get to work for the passed half hour, but something simple is going over my head. Look into the docs: https://www.gradio.app/docs/audio#initialization

After that, I think a system of orders/voices would be great for narrative structure. This would be an area I'm very familiar with, regular expression in python. We could make it so that different [bracket types] <trigger> [different assigned voices]

If we can make access easy (as few external downloads as possible) and really quality, useful mechanations like that a manifest reality, this will be, in my opinion, the best webUI. It's accessibility is already much better than most of the others, you've got five or so key parameters which are useful to use -- now it's just a matter of taking what you've already improved upon that's made this better than the original demo and starting a party of its own. That's how ya get your name out there bud. I'm here for it.
