### ISSUE TITLE
Custom model.

### ISSUE THREAD

**Issue by HobisPL** [daswer123/xtts-webui#22]
Can you tell me what needs to be changed to load a custom model? Unfortunately, when trying to load it, incorrect weights are appearing, probably the code is not adapted to loading custom models.

**Comment by daswer123** [comment]
You need to put the folder with the model in the `models` folder in this folder there should be 3 files: 
`model.pth` , `config.json`,`vocab.json`

**Comment by HobisPL** [comment]
> You need to put the folder with the model in the `models` folder in this folder there should be 3 files: `model.pth` , `config.json`,`vocab.json` After that, click Update and select the model in the list

ok, thx
