### ISSUE TITLE
Not an issue, a question on finetuning and creating models based on non-humanoid voices.

### ISSUE THREAD

**Issue by spike4379** [daswer123/xtts-webui#27]
Love how you have this set up and I'm not sure where I should be asking this and if you could direct me to a better place that would be awesome.

However my question is, how would you create a model based on a robotic voice? Say glados from portal 2 for example, or curie from fallout 4. There are many samples of 'robotic' voices that have some seriously top-notch sound effects processed into them that would be fantastic to clone.
I tried to do one voice but it honestly reverse engineered her voice and took the speech effects off, it even kept her german accent which was astonishing.
Is there a way to do this?

**Comment by daswer123** [comment]
Hi I haven't practiced models much, I know that for a good dataset you need 10 to 30 minutes of good sources.

With your question you should write to the official Coqui Discord, there are XTTS developers there who can advise you.
https://discord.gg/cxdqmh9a7u
