### ISSUE TITLE
Feature Enhancement Request: Integration of Inbuilt Studio Voices into UI

### ISSUE THREAD

**Issue by GOTHIC3020** [daswer123/xtts-webui#47]
The current version of xtts boasts support for 58 inbuilt studio voices. To enhance user experience and streamline accessibility, I propose integrating these voices directly into the user interface (UI).

![Speaker ids](https://github.com/daswer123/xtts-webui/assets/159919249/85ec1476-ca44-4be1-8fd3-480794a362d3)

**Comment by daswer123** [comment]
Hi, added support for these votes. You need to click this tick box and a selection of all these voices will appear in the speaker list

![image](https://github.com/daswer123/xtts-webui/assets/22278673/24ad0478-4619-4b38-a3da-1a62654d1bc3)

**Comment by GOTHIC3020** [comment]
Thank you, tested it works well.
