### ISSUE TITLE
Faster-whisper upgrade

### ISSUE THREAD

**Issue by KoljaB** [daswer123/xtts-webui#63]
First of all I great repo, I use it a lot, so thank you for creating this project.

Could you please upgrade faster-whisper version? 0.10.0 [hallucinates a lot](https://github.com/SYSTRAN/faster-whisper/issues/735#issuecomment-1980886525) (creates repetitions), while newer versions do not.

**Comment by daswer123** [comment]
Hi, glad my work is making a difference, your projects are great too )

Updated faster-whisper to 1.0.1

**Comment by KoljaB** [comment]
Thanks a lot
