### ISSUE TITLE
Uploading reference file always fails

### ISSUE THREAD

**Issue by Lartza** [daswer123/xtts-webui#8]
Traceback: https://gist.github.com/Lartza/fca95793ba0f1720a29d0c3d9ef8d8a3

A temp file is always successfully created, `temp\speaker_ref_ae9e3748-400e-4641-ba7c-0f3d39b990cd.wav` etc

**Comment by daswer123** [comment]
Looks like you don't have ffmpeg installed try installing it and try again

**Comment by Lartza** [comment]
Ah yes thanks, way past midnight so I got an xtts CLI issue mixed with this I probably could have figured that out myself.

Added to Path and issue fixed.

That said ffmpeg requirement is not documented anywhere and could potentially be downloaded by installer for the user. (Like many projects already include their own ffmpeg.exe)

**Comment by daswer123** [comment]
Yes you are right, I will add the requirements information and try to integrate ffmpeg into the installer
